### ISSUE TITLE
请问怎么使用这个脚本呢？

### ISSUE THREAD

**Issue by M1ddlzh** [Seryta/AHK-TrayIconHide#1]
你好，这个脚本时可以用来隐藏特定程序的托盘图标的吗？我下载了AutoHotKey，运行之后不知道该如何操作😅

**Comment by M1ddlzh** [comment]
![bug](https://user-images.githubusercontent.com/45971465/83011529-99696000-a04c-11ea-9faf-2ef08a6ef81c.png)
我找到了，是按下F2键对吧，但是隐藏一些图标后有这个Bug，有点难受。

**Comment by Seryta** [comment]
> ![bug](https://user-images.githubusercontent.com/45971465/83011529-99696000-a04c-11ea-9faf-2ef08a6ef81c.png)
> 我找到了，是按下F2键对吧，但是隐藏一些图标后有这个Bug，有点难受。

对不起我没想到有人能找到这个项目😂这几天出差也没注意。你详细说一下，是隐藏之后出现空白？目前我这边没有出现，你可以试试把要隐藏的程序，在Windows任务栏设置-选择哪些图标显示在任务栏上，把对应的程序图标关掉，这样的话我在脚本里写了每次设置隐藏的时候都会重新加载一次，理论上不会出现这种情况。

**Comment by Seryta** [comment]
> ![bug](https://user-images.githubusercontent.com/45971465/83011529-99696000-a04c-11ea-9faf-2ef08a6ef81c.png)
> 我找到了，是按下F2键对吧，但是隐藏一些图标后有这个Bug，有点难受。

试验之后回复给我结果，如果还有问题我会尽快尝试复现解决问题。

**Comment by M1ddlzh** [comment]
谢谢，就是运行脚本后按F2，选择要隐藏的图标，点击'OK'之后图标确实隐藏了，但是会有上图中的那个空白出现。
我按照你说的在任务栏设置关掉对应图标，但这样托盘左侧会出现上指箭头，空白消失了，但这个箭头能去掉吗？
![批注 2020-06-06 075859](https://user-images.githubusercontent.com/45971465/83930740-aa903a80-a7cb-11ea-8096-695e7bf336a4.png)

**Comment by M1ddlzh** [comment]
谢谢，就是运行脚本后按F2，选择要隐藏的图标，点击'OK'之后图标确实隐藏了，但是会有上图中的那个空白出现。
我按照你说的在任务栏设置关掉对应图标，但这样托盘左侧会出现上指箭头，空白消失了，但这个箭头能去掉吗？
![0606](https://user-images.githubusercontent.com/45971465/83930791-dc090600-a7cb-11ea-9b68-6fed8de48d6c.png)

**Comment by Seryta** [comment]
> 谢谢，就是运行脚本后按F2，选择要隐藏的图标，点击'OK'之后图标确实隐藏了，但是会有上图中的那个空白出现。
> 我按照你说的在任务栏设置关掉对应图标，但这样托盘左侧会出现上指箭头，空白消失了，但这个箭头能去掉吗？
> ![0606](https://user-images.githubusercontent.com/45971465/83930791-dc090600-a7cb-11ea-9b68-6fed8de48d6c.png)
> 

目前不能……

**Comment by M1ddlzh** [comment]
> > 谢谢，就是运行脚本后按F2，选择要隐藏的图标，点击'OK'之后图标确实隐藏了，但是会有上图中的那个空白出现。
> > 我按照你说的在任务栏设置关掉对应图标，但这样托盘左侧会出现上指箭头，空白消失了，但这个箭头能去掉吗？
> > ![0606](https://user-images.githubusercontent.com/45971465/83930791-dc090600-a7cb-11ea-9b68-6fed8de48d6c.png)
> 
> 目前不能……

那这个空白是去不掉吗？该脚本的本意只是将箭头中的图标隐藏吗？

**Comment by Seryta** [comment]
> > > 谢谢，就是运行脚本后按F2，选择要隐藏的图标，点击'OK'之后图标确实隐藏了，但是会有上图中的那个空白出现。
> > > 我按照你说的在任务栏设置关掉对应图标，但这样托盘左侧会出现上指箭头，空白消失了，但这个箭头能去掉吗？
> > > ![0606](https://user-images.githubusercontent.com/45971465/83930791-dc090600-a7cb-11ea-9b68-6fed8de48d6c.png)
> > 
> > 
> > 目前不能……
> 
> 那这个空白是去不掉吗？该脚本的本意只是将箭头中的图标隐藏吗？

对，我是将所有的图标都放在箭头里面的，所以本意也是隐藏里面的图标，至于外面的图标想去掉空白的话还需要作进一步的更改，这个需要了解一下更多的东西，我暂时没时间解决。

**Comment by M1ddlzh** [comment]
好的，谢谢啦😄！

**Comment by Seryta** [comment]
我想问下，你们是怎么找到我这个项目的……特别纳闷……
