### ISSUE TITLE
图标隐藏后会在最右侧出现空白位置

### ISSUE THREAD

**Issue by 536** [Seryta/AHK-TrayIconHide#2]
![image](https://user-images.githubusercontent.com/28009758/89706278-be584880-d996-11ea-8111-70f3b84c73f5.png)

**Comment by 536** [comment]
抱歉没看到已关闭的那个issue，建议在readme.md将此常见问题备注下，再次抱歉。

**Comment by Seryta** [comment]
> 抱歉没看到已关闭的那个issue，建议在readme.md将此常见问题备注下，再次抱歉。

不好意思，昨晚刚看到，本来以为这个功能只有我自己会用，所以就没有说明这些东西，现在改了……

**Comment by Seryta** [comment]
另外我想问下，你们是怎么找到我这个项目的……特别纳闷……

**Comment by 536** [comment]
QQ群

> 另外我想问下，你们是怎么找到我这个项目的……特别纳闷……

QQ群

**Comment by M1ddlzh** [comment]
hhh，我之前网上搜如何右键关闭chrome的标签，在知乎搜到了用AHK脚本，稍微了解后感觉是不是也可以用来隐藏图标，在github一搜“trayicon”就搜到了。



> 另外我想问下，你们是怎么找到我这个项目的……特别纳闷……

**Comment by Seryta** [comment]
> > 另外我想问下，你们是怎么找到我这个项目的……特别纳闷……
> 
> QQ群

哦哦～原来是群友

**Comment by Seryta** [comment]
> hhh，我之前网上搜如何右键关闭chrome的标签，在知乎搜到了用AHK脚本，稍微了解后感觉是不是也可以用来隐藏图标，在github一搜“trayicon”就搜到了。
> 
> > 另外我想问下，你们是怎么找到我这个项目的……特别纳闷……

哈哈厉害
